#! /bin/sh
if [ ! $(sudo echo 0) ]; then
	echo "use sudo"
	exit 1
fi

if [ $# -eq 0 ]; then
	echo "Give arguments"
	exit 1
fi

echo "zone \"$1.wout-vankerkhoven.sb.uclllabs.be\" {
	type master;
	file \"/etc/bind/zones/mrt-zones/db.$1.wout-vankerkhoven.sb.uclllabs.be\";
};" >> /etc/bind/named.conf.mrt-zones

touch /etc/bind/zones/mrt-zones/db.$1.wout-vankerkhoven.sb.uclllabs.be

echo "\$TTL 300
@ IN SOA ns.$1.wout-vankerkhoven.sb.uclllabs.be. host.wout-vankerkhoven.sb.uclllabs.be. (
	1 ; Serial
	900 ; Refresh
	120 ; Retry
	900 ; Expire
	300 ) ; Default TTL
; NAME SERVERS
@	IN	NS ns.wout-vankerkhoven.sb.uclllabs.be." > /etc/bind/zones/mrt-zones/db.$1.wout-vankerkhoven.sb.uclllabs.be

echo "$1	IN	NS	ns.wout-vankerkhoven.sb.uclllabs.be." >> /etc/bind/zones/db.wout-vankerkhoven.sb.uclllabs.be
echo "$1	IN	A	193.191.177.219" >> /etc/bind/zones/db.wout-vankerkhoven.sb.uclllabs.be

perl -i -pe '/Serial/ && s/(\d+)/$1+1 . $2/e' /etc/bind/zones/db.wout-vankerkhoven.sb.uclllabs.be

systemctl restart bind9.service
rndc reload

