#!/bin/bash

#check root
if [ "$EUID" -ne 0 ]
  then echo "not root"
  exit 0
fi

if [[ "$1" != "" ]]; then
  subdomain="$1"
else
  echo "subdomain not given"
  exit 0
fi

echo "" >> /etc/bind/named.conf.local
echo "// $subdomain config"  >> /etc/bind/named.conf.local
echo "zone $subdomain.wout-vankerkhoven.sb.uclllabs.be. {
	type master;
	file \"/etc/bind/zones/db.mrt.$subdomain.wout-vankerkhoven.sb.uclllabs.be\";
};" >> /etc/bind/named.conf.local

echo "\$TTL	300
@	IN	SOA	ns.$subdomain.wout-vankerkhoven.sb.uclllabs.be. admin.wout-vankerkhoven.sb.uclllabs.be. (
			    001		; Serial
			    300		; Refresh
			    300		; Retry
			2419200		; Expire
			    300)	; Negative Cache TTL
; Name servers
@       IN      NS      ns.$subdomain.wout-vankerkhoven.sb.uclllabs.be.
@       IN      NS      ns.wout-vankerkhoven.sb.uclllabs.be.
; A records
@	IN	A	193.191.177.219
ns	IN	A	193.191.177.219" >> $(echo "/etc/bind/zones/db.$subdomain.wout-vankerkhoven.sb.uclllabs.be")

echo "$subdomain       IN      NS      ns.wout-vankerkhoven.sb.uclllabs.be." >> /etc/bind/zones/db.wout-vankerkhoven.sb.uclllabs.be

old=$(grep "Serial" /etc/bind/zones/db.wout-vankerkhoven.sb.uclllabs.be | tr -s [:blank:] | cut -d ' ' -f 2)
new=$((old + 1))
sed -i "s/.*Serial.*/\t\t     $new ;Serial/g" /etc/bind/zones/db.wout-vankerkhoven.sb.uclllabs.be

systemctl restart bind9
